export { default as Comment } from '@/components/comment';
export { default as LikeButton} from '@/components/like-button';
export { default as Navbar } from '@/components/navbar';
export { default as Post } from '@/components/post';
export { default as UserAvatar } from "@/components/user-avatar";
export { default as Sidebar } from '@/components/sidebar';
export { default as MobileSidebar } from '@/components/mobile-sidebar';
export { default as SuggestedAccounts } from '@/components/suggested-accounts';
export { default as Footer } from '@/components/footer';
export { default as VideoItem } from '@/components/video-item';
export { default as Discover } from '@/components/discover';